# Generated by Django 4.1.6 on 2023-02-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doftDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pickups', models.CharField(max_length=10)),
                ('origins', models.CharField(max_length=50)),
                ('states_orign', models.CharField(max_length=5)),
                ('destinations', models.CharField(max_length=50)),
                ('states_dest', models.CharField(max_length=5)),
                ('weights', models.CharField(max_length=10)),
                ('distances', models.CharField(max_length=50)),
                ('truck_types', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='routingDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
