# Generated by Django 4.1.6 on 2023-02-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='usersDB',
        ),
    ]
